package mtg.insert

import mtg.persistance.EditionDAO
import mtg.model.Edition


object InsertEdition extends App {

  insertEditions()

  def insertEditions() {
    EditionDAO.upsert(new Edition("3rd Edition/Revised", "1003"))
    EditionDAO.upsert(new Edition("4th Edition", "1009"))
    EditionDAO.upsert(new Edition("5th Edition", "1015"))
    EditionDAO.upsert(new Edition("6th Edition", "1025"))
    EditionDAO.upsert(new Edition("7th Edition", "1037"))
    EditionDAO.upsert(new Edition("7th Edition FOIL", "1038"))
    EditionDAO.upsert(new Edition("8th Edition", "1053"))
    EditionDAO.upsert(new Edition("8th Edition FOIL", "1054"))
    EditionDAO.upsert(new Edition("9th Edition", "5023"))
    EditionDAO.upsert(new Edition("9th Edition FOIL", "5024"))
    EditionDAO.upsert(new Edition("10th Edition", "5061"))
    EditionDAO.upsert(new Edition("10th Edition FOIL", "5062"))
    EditionDAO.upsert(new Edition("Alara Reborn", "5131"))
    EditionDAO.upsert(new Edition("Alara Reborn FOIL", "5132"))
    EditionDAO.upsert(new Edition("Alliances", "1012"))
    EditionDAO.upsert(new Edition("Alpha", "1000"))
    EditionDAO.upsert(new Edition("Alternate 4th Edition", "5015"))
    EditionDAO.upsert(new Edition("Anthologies", "1068"))
    EditionDAO.upsert(new Edition("Antiquities", "1005"))
    EditionDAO.upsert(new Edition("Apocalypse", "1039"))
    EditionDAO.upsert(new Edition("Apocalypse FOIL", "1040"))
    EditionDAO.upsert(new Edition("Arabian Nights", "1004"))
    EditionDAO.upsert(new Edition("Archenemy Singles", "5190"))
    EditionDAO.upsert(new Edition("Archenemy Schemes", "5191"))
    EditionDAO.upsert(new Edition("Battle Royale", "1069"))
    EditionDAO.upsert(new Edition("Beatdown", "1070"))
    EditionDAO.upsert(new Edition("Beta", "1001"))
    EditionDAO.upsert(new Edition("Betrayers of Kamigawa", "5018"))
    EditionDAO.upsert(new Edition("Betrayers of Kam. FOIL", "5019"))
    EditionDAO.upsert(new Edition("BGS/PSA Graded", "5058"))
    EditionDAO.upsert(new Edition("Champions of Kamigawa", "5005"))
    EditionDAO.upsert(new Edition("Champions of Kam. FOIL", "5006"))
    EditionDAO.upsert(new Edition("Chronicles", "1062"))
    EditionDAO.upsert(new Edition("Coldsnap", "5040"))
    EditionDAO.upsert(new Edition("Coldsnap FOIL", "5041"))
    EditionDAO.upsert(new Edition("Coll. Edition Domestic", "5009"))
    EditionDAO.upsert(new Edition("Coll. Edition International", "5010"))
    EditionDAO.upsert(new Edition("Commander", "5213"))
    EditionDAO.upsert(new Edition("Conflux", "5116"))
    EditionDAO.upsert(new Edition("Conflux FOIL", "5117"))
    EditionDAO.upsert(new Edition("Darksteel", "1057"))
    EditionDAO.upsert(new Edition("Darksteel FOIL", "1058"))
    EditionDAO.upsert(new Edition("Deckmasters", "1071"))
    EditionDAO.upsert(new Edition("Dissension", "5037"))
    EditionDAO.upsert(new Edition("Dissension FOIL", "5038"))
    EditionDAO.upsert(new Edition("Duel Decks: Divine vs. Demonic", "5134"))
    EditionDAO.upsert(new Edition("Duel Decks: Elves vs. Goblins", "5082"))
    EditionDAO.upsert(new Edition("Duel Decks: Garruk vs. Liliana", "5176"))
    EditionDAO.upsert(new Edition("Duel Decks: Jace vs. Chandra", "5115"))
    EditionDAO.upsert(new Edition("Duel Decks: Knights vs. Dragons", "5209"))
    EditionDAO.upsert(new Edition("Duel Decks: Phyrexia vs. The Coalition", "5189"))
    EditionDAO.upsert(new Edition("Duels of the Planeswalkers", "5196"))
    EditionDAO.upsert(new Edition("Eventide", "5096"))
    EditionDAO.upsert(new Edition("Eventide Foil", "5097"))
    EditionDAO.upsert(new Edition("Exodus", "1019"))
    EditionDAO.upsert(new Edition("Fallen Empires", "1008"))
    EditionDAO.upsert(new Edition("Fifth Dawn", "5007"))
    EditionDAO.upsert(new Edition("Fifth Dawn FOIL", "5008"))
    EditionDAO.upsert(new Edition("From the Vault: Dragons", "5108"))
    EditionDAO.upsert(new Edition("From the Vault: Exiled", "5171"))
    EditionDAO.upsert(new Edition("From the Vault: Relics", "5194"))
    EditionDAO.upsert(new Edition("Future Sight", "5055"))
    EditionDAO.upsert(new Edition("Future Sight FOIL", "5056"))
    EditionDAO.upsert(new Edition("Guildpact", "5035"))
    EditionDAO.upsert(new Edition("Guildpact FOIL", "5036"))
    EditionDAO.upsert(new Edition("Homelands", "1011"))
    EditionDAO.upsert(new Edition("Ice Age", "1010"))
    EditionDAO.upsert(new Edition("Innistrad", "5215"))
    EditionDAO.upsert(new Edition("Innistrad FOIL", "5216"))
    EditionDAO.upsert(new Edition("Invasion", "1033"))
    EditionDAO.upsert(new Edition("Invasion FOIL", "1034"))
    EditionDAO.upsert(new Edition("Judgment", "1045"))
    EditionDAO.upsert(new Edition("Judgment FOIL", "1046"))
    EditionDAO.upsert(new Edition("Legends", "1006"))
    EditionDAO.upsert(new Edition("Legions", "1049"))
    EditionDAO.upsert(new Edition("Legions FOIL", "1050"))
    EditionDAO.upsert(new Edition("Lorwyn", "5064"))
    EditionDAO.upsert(new Edition("Lorwyn FOIL", "5065"))
    EditionDAO.upsert(new Edition("Magic 2010 Singles", "5137"))
    EditionDAO.upsert(new Edition("Magic 2010 FOIL", "5138"))
    EditionDAO.upsert(new Edition("Magic 2011 Singles", "5192"))
    EditionDAO.upsert(new Edition("Magic 2011 FOIL", "5193"))
    EditionDAO.upsert(new Edition("Magic 2012 Singles", "5211"))
    EditionDAO.upsert(new Edition("Magic 2012 FOIL", "5212"))
    EditionDAO.upsert(new Edition("Mercadian Masques", "1027"))
    EditionDAO.upsert(new Edition("Merc. Masques FOIL", "1028"))
    EditionDAO.upsert(new Edition("Mirage", "1013"))
    EditionDAO.upsert(new Edition("Mirrodin", "1055"))
    EditionDAO.upsert(new Edition("Mirrodin FOIL", "1056"))
    EditionDAO.upsert(new Edition("Mirrodin Besieged", "5202"))
    EditionDAO.upsert(new Edition("Mirrodin Besieged FOIL", "5203"))
    EditionDAO.upsert(new Edition("Morningtide", "5083"))
    EditionDAO.upsert(new Edition("Morningtide FOIL", "5084"))
    EditionDAO.upsert(new Edition("Nemesis", "1029"))
    EditionDAO.upsert(new Edition("Nemesis FOIL", "1030"))
    EditionDAO.upsert(new Edition("New Phyrexia", "5207"))
    EditionDAO.upsert(new Edition("New Phyrexia FOIL", "5208"))
    EditionDAO.upsert(new Edition("Odyssey", "1041"))
    EditionDAO.upsert(new Edition("Odyssey FOIL", "1042"))
    EditionDAO.upsert(new Edition("Onslaught", "1047"))
    EditionDAO.upsert(new Edition("Onslaught FOIL", "1048"))
    EditionDAO.upsert(new Edition("Oversized Magic Cards", "1073"))
    EditionDAO.upsert(new Edition("Planar Chaos", "5049"))
    EditionDAO.upsert(new Edition("Planar Chaos FOIL", "5050"))
    EditionDAO.upsert(new Edition("Planechase Planes", "5175"))
    EditionDAO.upsert(new Edition("Planechase Singles", "5174"))
    EditionDAO.upsert(new Edition("Planeshift", "1035"))
    EditionDAO.upsert(new Edition("Planeshift FOIL", "1036"))
    EditionDAO.upsert(new Edition("Portal I", "1059"))
    EditionDAO.upsert(new Edition("Portal II", "1060"))
    EditionDAO.upsert(new Edition("Portal: Three Kingdoms", "1061"))
    EditionDAO.upsert(new Edition("Premium Slivers", "5186"))
    EditionDAO.upsert(new Edition("Pro Player Cards", "5034"))
    EditionDAO.upsert(new Edition("Promotional Cards", "1078"))
    EditionDAO.upsert(new Edition("Promotional Cards FOIL", "1079"))
    EditionDAO.upsert(new Edition("Prophecy", "1031"))
    EditionDAO.upsert(new Edition("Prophecy FOIL", "1032"))
    EditionDAO.upsert(new Edition("Ravnica", "5026"))
    EditionDAO.upsert(new Edition("Ravnica FOIL", "5027"))
    EditionDAO.upsert(new Edition("Rise of the Eldrazi", "5187"))
    EditionDAO.upsert(new Edition("Rise of the Eldrazi FOIL", "5188"))
    EditionDAO.upsert(new Edition("Saviors of Kamigawa", "5020"))
    EditionDAO.upsert(new Edition("Saviors of Kam. FOIL", "5021"))
    EditionDAO.upsert(new Edition("Scars of Mirrodin", "5197"))
    EditionDAO.upsert(new Edition("Scars of Mirrodin FOIL", "5198"))
    EditionDAO.upsert(new Edition("Scourge", "1051"))
    EditionDAO.upsert(new Edition("Scourge FOIL", "1052"))
    EditionDAO.upsert(new Edition("Shadowmoor", "5094"))
    EditionDAO.upsert(new Edition("Shadowmoor FOIL", "5095"))
    EditionDAO.upsert(new Edition("Shards of Alara", "5106"))
    EditionDAO.upsert(new Edition("Shards of Alara FOIL", "5107"))
    EditionDAO.upsert(new Edition("Starter 1999", "1063"))
    EditionDAO.upsert(new Edition("Starter 2000", "5014"))
    EditionDAO.upsert(new Edition("Stronghold", "1018"))
    EditionDAO.upsert(new Edition("Summer Magic", "5224"))
    EditionDAO.upsert(new Edition("Tempest", "1017"))
    EditionDAO.upsert(new Edition("The Dark", "1007"))
    EditionDAO.upsert(new Edition("Time Spiral", "5042"))
    EditionDAO.upsert(new Edition("Time Spiral FOIL", "5043"))
    EditionDAO.upsert(new Edition("Token Cards (SCG.com)", "1080"))
    EditionDAO.upsert(new Edition("Torment", "1043"))
    EditionDAO.upsert(new Edition("Torment FOIL", "1044"))
    EditionDAO.upsert(new Edition("Unglued", "1064"))
    EditionDAO.upsert(new Edition("Unhinged", "5016"))
    EditionDAO.upsert(new Edition("Unhinged FOIL", "5017"))
    EditionDAO.upsert(new Edition("Unlimited", "1002"))
    EditionDAO.upsert(new Edition("Urza's Destiny", "1023"))
    EditionDAO.upsert(new Edition("Urza's Destiny FOIL", "1024"))
    EditionDAO.upsert(new Edition("Urza's Legacy", "1021"))
    EditionDAO.upsert(new Edition("Urza's Legacy FOIL", "1022"))
    EditionDAO.upsert(new Edition("Urza's Saga", "1020"))
    EditionDAO.upsert(new Edition("Vanguard", "1074"))
    EditionDAO.upsert(new Edition("Visions", "1014"))
    EditionDAO.upsert(new Edition("Weatherlight", "1016"))
    EditionDAO.upsert(new Edition("Worldwake", "5177"))
    EditionDAO.upsert(new Edition("Worldwake FOIL", "5178"))
    EditionDAO.upsert(new Edition("Zendikar", "5172"))
    EditionDAO.upsert(new Edition("Zendikar FOIL", "5173"))
  }
}